trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @nestjs/cli
      npm install
    displayName: 'npm install'

  - script: |
      npm run build
    displayName: 'Build Project'

  - script: |
      npm test -- --coverage
    displayName: 'Run Unit Tests'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'coverage/test-results.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
    displayName: 'Publish Test Results'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'nestJs-platform'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'

  - task: Docker@2
    inputs:
      containerRegistry: 'docker'
      repository: 'mohamedamine1/backend'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: 'backend-pfe' # Specify your tag here
    displayName: 'Build and Push Docker Image'
