apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /reactapp(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-react-app-service
                port:
                  number: 80
          - path: /nestapp(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-nest-app-service
                port:
                  number: 80
          - path: /mongodb(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mongodb-service
                port:
                  number: 27017
          - path: /redis(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: redis
                port:
                  number: 6379
