apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-nest-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: example.com
      http:
        paths:
          - path: /nestapp/
            pathType: Prefix
            backend:
              service:
                name: my-nest-app-service
                port:
                  number: 80
