apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    argocd.argoproj.io/instance: back-azure
  name: mongodb-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
