apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-infracost
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/infracost # Assurez-vous que ce chemin existe sur vos nœuds
  storageClassName: manual
  volumeMode: Filesystem
