apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-terraform
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/terraform # Assurez-vous que ce chemin existe sur vos nœuds Kubernetes
  storageClassName: manual
