apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
type: Opaque
data:
  AZURE_CLIENT_ID: MTYyODhiOTEtYjM0ZS00MTIyLTk4ZjktZDVmODc5MTlhYzMw
  AZURE_TENANT_ID: YjVkZGI1ZjYtYzcxMy00OGU5LWE5M2QtZDlmYTdkNmQ2YWU4
  AZURE_CLIENT_SECRET: OWY2MGRkYTgtNDJiOS00NmE1LWEyYTctNTY3YWRlMTZiZWU2
