apiVersion: v1
kind: Service
metadata:
  name: my-nest-app-service
spec:
  selector:
    app: my-nest-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6379
