apiVersion: v1
kind: Service
metadata:
  name: my-nest-app-service
spec:
  selector:
    app: my-nest-app
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
spec:
  selector:
    app: my-react-app
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: infracost-service
spec:
  selector:
    app: infracost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
