apiVersion: apps/v1
kind: HelmRelease
metadata:
  name: nestjs-mongodb-redis
spec:
  releases:
    # Release for Nest.js application
    - name: my-nest-app
      chart:
        repository: https://charts.example.com/stable
        name: my-nest-app
        version: 1.0.0
      values:
        replicaCount: 3
        image:
          repository: backend-azure
          tag: backend
          pullPolicy: IfNotPresent
        service:
          name: my-nest-app-service
          type: LoadBalancer
          port: 3002
        env:
          - name: MONGO_URI
            value: 'mongodb+srv://amine:Hamidou123@cluster0.upvcmiw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: '6379'

    # Release for MongoDB
    - name: mongodb
      chart:
        repository: https://charts.example.com/stable
        name: mongodb
        version: 1.0.0
      values:
        replicaCount: 1
        image:
          repository: mongo
          tag: latest
          pullPolicy: IfNotPresent
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: admin

    # Release for Redis
    - name: redis
      chart:
        repository: https://charts.example.com/stable
        name: redis
        version: 1.0.0
      values:
        replicaCount: 1
        image:
          repository: redis
          tag: latest
          pullPolicy: IfNotPresent
        service:
          name: redis-service
          type: ClusterIP
          port: 6379
