apiVersion: apps/v1
kind: HelmRelease
metadata:
  name: nestjs-mongodb
spec:
  releases:
    # Release pour l'application Nest.js
    - name: my-nest-app
      chart:
        repository: https://charts.example.com/stable
        name: my-nest-app
        version: 1.0.0
      values:
        - name: my-nest-app
          replicaCount: 3
          image:
            repository: backend-azure
            tag: backend
            pullPolicy: IfNotPresent
          service:
            name: my-nest-app-service
            type: LoadBalancer
            port: 3002

    # Release pour MongoDB
    - name: mongodb
      chart:
        repository: https://charts.example.com/stable
        name: mongodb
        version: 1.0.0
      values:
        - name: mongodb
          replicaCount: 1
          image:
            repository: mongo
            tag: latest
            pullPolicy: IfNotPresent
          env:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
